### PR TITLE
Add option to configure TableView style for storyboard usage

### PR DESCRIPTION
**Pull request by Tobisaninfo**
This pull requests add the option to configure the TableView style in the initializer used by storyboards.

I used the new initializer in my ViewController the following way:
```swift
    public required init?(coder: NSCoder) {
        super.init(coder: coder, style: .insetGrouped)
    }
```

### CODE REVIEW

**Review by bcylin — COMMENTED** [review]
@Tobisaninfo thanks much for the pull request.

This lib wasn't designed to use with storybaords so it's a bit tricky. I think the proper solution is to make the table view an `@IBOutlet` and set `view = tableView` when `func loadView()`.

One of the simpler approaches for now is to follow UITableViewController by making the table view `readwrite`:

```diff
class QuickTableViewController {
-  open private(set) var tableView: UITableView = UITableView(frame: .zero, style: .grouped)
+  open var tableView = UITableView(frame: .zero, style: .grouped)
}
```

Then it's much easier to override the table veiw for you needs:

```swift
required init?(coder: NSCoder) {
  super.init(coder: coder)
  tableView = UITableView(frame: .zero, style: .insetGrouped)
}
```

Can you make the changes and see if it works? Thanks.

**Comment by Tobisaninfo** [comment]
Hi Ben,

thanks for your feedback.
I changed my edits to your simpler approach. I tested the changes in my own project and it works good for me.
Please let me know, if I can do anything better.

**Comment by bcylin** [comment]
Thanks for updating the PR 👍

**Comment by Tobisaninfo** [comment]
Hi @bcylin,

I would like to ask you for a favour. Maybe you heard about the _Hacktoberfest_ (https://hacktoberfest.digitalocean.com/details). It is about open source contribution and doing something good for community and our planet. So I wonder if you might add the label `hacktoberfest-accepted` to this pull request. This will help me, to achieve the goal of the Hacktoberfest.

Thanks
Tobias

**Comment by bcylin** [comment]
@Tobisaninfo sure, thank you for creating the pull request.

**Pull request merged**
