### PR TITLE
Swift 5 migration

### PR DESCRIPTION
**Pull request by getaaron**
All tests pass.

- Migrated sample project and QuickTableViewController source code to Swift 5
- Migrated `English` localization to `en`
- Removed access modifiers considered redundant in Swift 5
- Use `.default` for potential future unknown `UITableViewCellStyle`s using Swift 5's new `@unknown default` for enums imported from C-based languages
- Updated SwiftLint to 0.32.0 (version which supports Swift 5)

Out of scope:

- Updating Quick and Nimble to a newer version

### CODE REVIEW

**Comment by getaaron** [comment]
Seems like the only untested code is the addition of `@unknown default: return ".default"`. Probably not worth writing a test for that? Seems like you'd have to force the Objective-C Runtime to send an illegal enum case or something?

**Comment by getaaron** [comment]
@bcylin I could use your help in resolving these errors when building the docs:

```
❌  error: /Users/travis/build/bcylin/QuickTableViewController/Pods/SwiftLint/Carthage/Checkouts/xcconfigs/Base/Configurations/Release.xcconfig: unable to open file (in project "SwiftLint") (in target 'SwiftLintFramework')
❌  error: /Users/travis/build/bcylin/QuickTableViewController/Pods/SwiftLint/Carthage/Checkouts/xcconfigs/Mac OS X/Mac-Framework.xcconfig: unable to open file (in target "SwiftLintFramework" in project "SwiftLint") (in target 'SwiftLintFramework')
❌  error: /Users/travis/build/bcylin/QuickTableViewController/Pods/SwiftLint/Carthage/Checkouts/xcconfigs/Base/Configurations/Release.xcconfig: unable to open file (in project "SwiftLint") (in target 'SwiftLintFramework')
❌  error: /Users/travis/build/bcylin/QuickTableViewController/Pods/SwiftLint/Carthage/Checkouts/xcconfigs/Mac OS X/Mac-Framework.xcconfig: unable to open file (in target "SwiftLintFramework" in project "SwiftLint") (in target 'SwiftLintFramework')
❌  error: /Users/travis/build/bcylin/QuickTableViewController/Pods/SwiftLint/Carthage/Checkouts/xcconfigs/Base/Configurations/Release.xcconfig: unable to open file (in project "SwiftLint") (in target 'SwiftLintFramework')
❌  error: /Users/travis/build/bcylin/QuickTableViewController/Pods/SwiftLint/Carthage/Checkouts/xcconfigs/Mac OS X/Mac-Framework.xcconfig: unable to open file (in target "SwiftLintFramework" in project "SwiftLint") (in target 'SwiftLintFramework')
```

**Comment by bcylin** [comment]
Hi @getaaron, thank you very much for this pull request! No worries about the untested `@unknown default`.

The `Pods/SwiftLint/Carthage` error is a bit weird. Pod installed [`portable_swiftlint.zip`](https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/0/1/SwiftLint/0.32.0/SwiftLint.podspec.json) should only contain an executable:

```
Pods/SwiftLint
├── LICENSE
└── swiftlint
```

Can you try https://github.com/getaaron/QuickTableViewController/compare/getaaron:swift-5...bcylin:swift-5 and see if it works?

**Comment by getaaron** [comment]
Nice, you beat me to it @bcylin! What happened with index vs. firstIndex?

**Comment by bcylin** [comment]
I've still got some issue with `CwlPreconditionTesting.h` in the testing target. 😅 

What's about index vs. firstIndex? Is it https://github.com/bcylin/QuickTableViewController/pull/38/commits/369e65200e5dd46e2a82c04b442a508d429ea5ba#diff-457d78d98b22052d0d7662f3f9506a44?

**Pull request merged**
